### ISSUE TITLE
After adding "-headless", workers cannot connect to locust master.

### ISSUE THREAD

**Issue by lsl-2020** [deliveryhero/helm-charts#108]
Hi,

I have deployed this helm chart in AKS cluster. And it works very well. Here is my deployment command in Azure cloud shell:
```
helm install my-loadtest-release ./ \
  --set worker.hpa.enabled=true \
  --set worker.replicas=3 \
  --set service.type=LoadBalancer
```
(Current directory is /helm-charts/stable/locust, and it worked very well with the webpage-mode.)

However, after I simply added "--headless" in master-deployment.yaml, the workers cannot connect to locust master. Here is where I changed:
```
{{ else if .Values.master.args_include_default }}
        args:
          - --master
          - --headless
          - --locustfile=/mnt/locust/{{ .Values.loadtest.locust_locustfile }}
          - --host={{ .Values.loadtest.locust_host }}
          - --loglevel={{ .Values.master.logLevel }}
```

I just added one line "- --headless", and all connection from worker to master failed:
![image](https://user-images.githubusercontent.com/68244035/106224695-c050e500-621e-11eb-9a0d-ffa19c8d9546.png)

What I have tried:
1. I have tried combination of "--run-time", "--spawn-rate", "--run-time", "--expected-workers", all end up with same results.
2. I have tried changing service name from {{ template "locust.fullname" . }} to {{ template "locust.fullname" . }}-master, same with master's name. Still the same.
3. I have tried to manully bind master-port using "--master-bind-port" in master-deployment.yaml, and "--master-host", "--master-port" in worker-deployment.yaml" (In all kinds of combinations). Still the same.
4. I have tried to use Environment variables to do all mentioned changes, and get the same results.

I think it is neccessary to be able to use headless mode for automated load test. So much appreciated if anyone gets curious and help with this issue. Thank you!

My working environments:
- Resource: An AKS (Azure Kubernetes Service) Cluster
- Command portal: Azure Cloud Shell

**Comment by max-rocket-internet** [comment]
Hi @lsl-2020

It's because there is a `readinessProbe` for the master here: https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/templates/master-deployment.yaml#L103-L110

If you use headless mode, the HTTP server isn't started, the `readinessProbe` will fail, the pod will not receive requests via the k8s service.

> I think it is neccessary to be able to use headless mode for automated load test.

I agree.

Both probes needs to be disabled in headless mode. Or we switch them to `TCP: 5557`. Perhaps we add a `headless` option to values that is a bolean?

**Comment by lsl-2020** [comment]
Hi Max,

Thanks for the hint. To find the root cause for failure, I took a simple step by disabling both probes and the chart works well with headless mode afterwards. Thank you for your kind help!


> Or we switch them to `TCP: 5557`. Perhaps we add a `headless` option to values that is a bolean?

I think it might be a more elegant way to add a `headless` option and to judge its value for pipelines in `readinessProbe` instead of just switching ports. I am wondering if you have plans to include these in your next PR?

**Comment by max-rocket-internet** [comment]
@lsl-2020 cool, can you test this PR? https://github.com/deliveryhero/helm-charts/pull/109

**Comment by lsl-2020** [comment]
@max-rocket-internet  Love to. I have already posted my test result and some suggestions under PR #109
