### ISSUE TITLE
memory and cpu limit/request needed for node-problem-detector chart

### ISSUE THREAD

**Issue by bilalcaliskan** [deliveryhero/helm-charts#125]

**Comment by max-rocket-internet** [comment]
For what chart @bilalcaliskan?

**Comment by bilalcaliskan** [comment]
@max-rocket-internet  sorry for the descriptionless issue. I mean [node-problem-detector](https://github.com/deliveryhero/helm-charts/tree/master/stable/node-problem-detector). I can open a PR for that if it's OK.

Regards.

**Comment by bilalcaliskan** [comment]
There is already a configuration for that [here](https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/templates/daemonset.yaml#L87). Closing issue now. Sorry for your time.
