### ISSUE TITLE
[stable/cluster-overprovisioner] Definitions of the PodDisruptionBudget in the Helm Chart

### ISSUE THREAD

**Issue by SatoruItaya** [deliveryhero/helm-charts#173]
I think the `PodDisruptionBudget` is necessary to evict cluster-overprovisioner pods normally.
So, I would like to define  the `PodDisruptionBudget` in the Helm Chart and add a parameter which controls if Helm Chart creates `PodDisruptionBudget` or not.

**Comment by max-rocket-internet** [comment]
> I think the PodDisruptionBudget is necessary to evict cluster-overprovisioner pods normally.

I don't think so, I think the pod priority is enough? PRs welcome anyway 🙂

**Comment by SatoruItaya** [comment]
The reason why I thought is Cluster autoscaler does not work in scale-down.
Cluster autoscaler stops terminating nodes if pods without PDB works on them.

**Comment by max-rocket-internet** [comment]
Oh I see, so the cluster-overprovisioner pods prevent node scale down. Well test using a PDB locally and if it works then please open a PR 🚀

**Comment by SatoruItaya** [comment]
I see, I will create a PR later.
Thanks for your response.
