### ISSUE TITLE
Could not find any locustfile! Ensure file ends in '.py'

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [deliveryhero/helm-charts#180]
Hello!

I follow the instructions in README.
Created configmaps from my local files (validated that they were created successfully):
`kubectl create configmap my-loadtest-locustfile --from-file locustfile.py`
`kubectl create configmap my-loadtest-lib --from-file lib`

This is the content of `locustfile.py`:
```
from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(1, 2.5)

    @task
    def call_a(self):
        self.client.get("/a")
```

The contents or `lib` folder were copied from the example.

Then I install Helm chart with the command from README:
```
helm install locust deliveryhero/locust \
   --set loadtest.name=my-loadtest \
   --set loadtest.locust_locustfile_configmap=my-loadtest-locustfile \
   --set loadtest.locust_lib_configmap=my-loadtest-lib
```

After this I see the following error in master and worker pods:
`Could not find any locustfile! Ensure file ends in '.py' and see --help for available options.`

Please help :-)
I am just the README steps and it is not working...

**Comment by dmitrii-listvin** [comment]
I had the same problem and found a solution:
1. Rename your locustfile ("locustfile.py") to "main.py"
2. Remove configmap my-loadtest-locustfile
3. Recreate it again with `kubectl create configmap my-loadtest-locustfile --from-file locustfile.py`
4. Try installing helm chart again

It worked for me.
