### ISSUE TITLE
Source for images

### ISSUE THREAD

**Issue by hamza-tumturk** [deliveryhero/helm-charts#181]
Hi,
I'm trying to find the source code for the image `940776968316.dkr.ecr.eu-west-1.amazonaws.com/deliveryhero/kubecost-reports-exporter`.
Is that open sourced anywhere?
Thanks!

**Comment by max-rocket-internet** [comment]
Hey @nyambati can you either update the chart to use a public image, make our image public or add a Dockerfile to this chart?

**Comment by nyambati** [comment]
@max-rocket-internet @hamza-tumturk I have updated the chart to include the source code and the reference to public repository. changes can be found in this PR #183

**Comment by max-rocket-internet** [comment]
Resolved in https://github.com/deliveryhero/helm-charts/pull/183
