### ISSUE TITLE
[stable/locust] Installation gets stuck at ContainerCreating

### ISSUE THREAD

**Issue by roshan8** [deliveryhero/helm-charts#182]
I tried to install the Locust from stable/locust. However, The installation gets stuck every time with pods getting stuck in `ContainerCreating` state.

```
 ~/helm-chart | master ?2  k logs -f locust-release-master-5d46dbd476-q4lkp                                                                                                          ok | 4s | k8-staging kube
Error from server (BadRequest): container "locust" in pod "locust-release-master-5d46dbd476-q4lkp" is waiting to start: ContainerCreating
```

```
  Normal   Scheduled    29m                   default-scheduler  Successfully assigned default/locust-release-master-5d46dbd476-q4lkp to gke-k8-staging-k8-staging-pool-9b8dd468-16k0
  Warning  FailedMount  24m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[locustfile lib], unattached volumes=[config locust-release-master-token-75pk7 locustfile lib]: timed out waiting for the condition
  Warning  FailedMount  19m (x13 over 29m)    kubelet            MountVolume.SetUp failed for volume "locustfile" : configmap "my-loadtest-locustfile" not found
  Warning  FailedMount  13m (x4 over 27m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[locustfile lib], unattached volumes=[locustfile lib config locust-release-master-token-75pk7]: timed out waiting for the condition
  Warning  FailedMount  9m7s (x2 over 22m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[locustfile lib], unattached volumes=[locust-release-master-token-75pk7 locustfile lib config]: timed out waiting for the condition
  Warning  FailedMount  2m44s (x21 over 29m)  kubelet            MountVolume.SetUp failed for volume "lib" : configmap "my-loadtest-lib" not found
```

Initially I tried creating configMap before running helm install. Later just installed chart without configmap(assuming it should take the default locustfile). Both the time installation failed. 

P.S: I'm using GKE cluster.

**Comment by roshan8** [comment]
@max-rocket-internet Also tried the official locust repo. It's throwing 404 while adding the repo.

**Comment by max-rocket-internet** [comment]
Hi @roshan8, I think the error here is clear?

```
configmap "my-loadtest-locustfile" not found
configmap "my-loadtest-lib" not found
```

You need to create 2 configmaps with these names 🙂

> Also tried the official locust repo

Which repo?

**Comment by roshan8** [comment]
@max-rocket-internet This is the repo throwing 404: https://github.com/locustio/helm-chart

As per the [readme](https://github.com/locustio/helm-chart/blob/master/README.md), The chart would use the default config if we don't create configmap explicitely. So that threw me off a bit!

> By default it will install using an example locustfile and lib from stable/locust/locustfiles/example. When you want to provide your own locustfile, you will need to create 2 configmaps using the structure from that example:

Also, I'm unable to create locustfile configmap from .py file.
```
kubectl create configmap my-loadtest-locustfile --from-file /Users/xyz/main.py
```
This command fails to create config map but throws no error.

**Comment by rganeshsharma** [comment]
Hi Guys please throw some light here...I am trying to integrate Prometheus with Node-Problem-Dectector and want to know which IP to assign to Prometheus Exporter in values.yaml ? 

Applying Prometheus Node Exporter IP gives error that IP Cannot be binded. May I know what IP to assign for Prometheus Exporter. Please Help Guys.

**Comment by roshan8** [comment]
@rganeshsharma Please don't spam on unrelated issues. Have some patience till maintainers address your [issue](https://github.com/deliveryhero/helm-charts/issues/184)

**Comment by rganeshsharma** [comment]
@roshan8 grow up son :)

**Comment by max-rocket-internet** [comment]
> This is the repo throwing 404: https://github.com/locustio/helm-chart

This repo was never setup correctly. See https://github.com/locustio/helm-chart/issues/2

I support this copy of the locust chart here in this repo, not the other one.

> This command fails to create config map but throws no error.

If the configmap fails to create then that is your problem. I will close this now.
