### ISSUE TITLE
Extra command args for master + Using basic auth causes failure for readinessProbe

### ISSUE THREAD

**Issue by yosri2005** [deliveryhero/helm-charts#196]
Hello,

I noticed a couple items when using this chart, let me know if they should be broken up into two separate issues, but for now...

1) in the values.yaml, when I have `args_include_default: true`, and I want to include extra arguments in `args: []`, it ends up removing the default arguments when I really expected it to add to them. I can see in the template how the if-condition is causing that, but wondering now if that is intended behaviour, or instead should be changed so that `args` are added above the default args.

2) When I enabled basic authentication on the UI, which I performed just by passing a `web-auth` arg to master, the deployment failed due to
```Readiness probe failed: HTTP probe failed with statuscode: 401```

Now, of course  one can enable basic authentication on a readiness probe, but where our chart is basically an umbrella chart pointing to this one, I don't have as much control. It would be nice if we could enable basic auth more concretely through the  values.yaml file, and the template know when it is enabled and adjust the readinessProbe accordingly. Let me know if there's another way to get this working.

Thanks

**Comment by max-rocket-internet** [comment]
Hi @yosri2005 

1. I think `args_include_default` is intended to be used like "use the default args" or "you provide all args yourself". Not a mix. So if you want extra args then you must provide them all in that case.
2. I see. I think it might be worth adding all probes to values.yaml or adding an option to disable probes completely. This would solve the problem for you.

> I don't have as much control

Of course you do, you can make a PR to this chart 🙂

> It would be nice if we could enable basic auth more concretely through the values.yaml file, and the template know when it is enabled and adjust the readinessProbe accordingly. Let me know if there's another way to get this working.

Sounds great, open a PR!

**Comment by yosri2005** [comment]
Thanks @max-rocket-internet, I will look into it!

**Comment by yosri2005** [comment]
@max-rocket-internet [Pull Request 199](https://github.com/deliveryhero/helm-charts/pull/199) is now open for you review. Thank you.
