### ISSUE TITLE
Maybe update the default locust version?

### ISSUE THREAD

**Issue by cyberw** [deliveryhero/helm-charts#219]
Latest release is now 2.1 :) @max-rocket-internet

**Comment by max-rocket-internet** [comment]
PRs welcome 😅

**Comment by cyberw** [comment]
I could do that, but I have no way of testing it so... do you still want me to?

**Comment by max-rocket-internet** [comment]
@cyberw I mean the community will do it when it's wanted, the locust chart here has many contributors. I am on holiday until next week but sure you can submit it if you want, the CI will test it for you 🙂
