### ISSUE TITLE
[Node-problem-detector] Streaming of warnings in namespace events 

### ISSUE THREAD

**Issue by ahmedmfadel** [deliveryhero/helm-charts#234]
I tried deploying node-problem-detector using helm chart and a custom values.yaml file but I got these warnings in the events 

`87s         Warning   FailedMount              pod/node-problem-detector-crcn4   MountVolume.SetUp failed for volume "custom-config" : failed to sync configmap cache: timed out waiting for the condition

87s         Warning   FailedMount              pod/node-problem-detector-crcn4   MountVolume.SetUp failed for volume "node-problem-detector-token-wqv6s" : failed to sync secret cache: timed out waiting for the condition

87s         Warning   FailedMount              pod/node-problem-detector-zvqfc   MountVolume.SetUp failed for volume "custom-config" : failed to sync configmap cache: timed out waiting for the condition

85s         Warning   FailedToUpdateEndpoint   endpoints/node-problem-detector   Failed to update endpoint node-problem-detector/node-problem-detector: Operation cannot be fulfilled on endpoints "node-problem-detector": the object has been modified; please apply your changes to the latest version and try again`

For the first three events I think this happened because the service account doesn't have permission to mount secrets or configMaps but I don't understand the reason behind the last event.

**Comment by max-rocket-internet** [comment]
Hi @ahmedmfadel, you can always use a previous version of the chart until this issue is fixed.

PRs welcome 🙂
