### ISSUE TITLE
[stable/locust] Artifacthub.io's Image Security Rating is F for this chart

### ISSUE THREAD

**Issue by thesolution** [deliveryhero/helm-charts#268]
This might be a locustio/locust issue since this chart is using the canonical locustio docker image.
https://artifacthub.io/packages/helm/deliveryhero/locust 

It is a cause for concern when using this chart, but the other locust charts on the site don't show the "image security rating".

**Comment by max-rocket-internet** [comment]
Thanks @thesolution but as you noted, we don't maintain the docker image, just the chart. It's best create an issue in the locust repo and they can follow it up there 🙂

**Comment by max-rocket-internet** [comment]
> the other locust charts on the site don't show the "image security rating".

I think this might be because they are custom built images and not pre-scanned by whatever service Artifacthub uses.
