### ISSUE TITLE
[pg-repack-scheduler] Keep Looping

### ISSUE THREAD

**Issue by allenheydari2019** [deliveryhero/helm-charts#287]
The logic on .sh file keeps looping around the same table and won't go to the next. It keeps adding J to the pg_repack command for infinite loop.

**Comment by max-rocket-internet** [comment]
@allenheydari2019 what chart are you talking about? there's over 40 charts in this repo...

**Comment by allenheydari2019** [comment]
Hey man,

 I am talking about your cool run_pg_packer.sh.

When I run it as a stand alone script in corntab it keeps looping through
one table and adds -j infinitely.

**Comment by max-rocket-internet** [comment]
Perhaps @Naginder-Singh can help you 🙂

**Comment by allenheydari2019** [comment]
Would you help please? 🙃

**Comment by allenheydari2019** [comment]
Any hope?

**Comment by max-rocket-internet** [comment]
@allenheydari2019 all the code is in the chart, including the dockerfile and scripts. You are welcome to debug it yourself and creating a PR.
