### ISSUE TITLE
Latest Version of Locust uses venv

### ISSUE THREAD

**Issue by jz-wilson** [deliveryhero/helm-charts#300]
Hello,

The latest version of locust uses venv so its not possible to run the pip install package step if they are required. I had to update the locustcmd value to `/opt/venv/bin/locust`. But when starting the container it fails. We need an option to specify parameters for pip too.

Error on container on start:
``` 
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

**Comment by akuzni2** [comment]
is there any update on this? I'm encountering the same issue

**Comment by max-rocket-internet** [comment]
Please see: https://github.com/deliveryhero/helm-charts/issues/356

I think it's now working.
