### ISSUE TITLE
Not able to stop pods once locust tests are over 

### ISSUE THREAD

**Issue by honeychawla2** [deliveryhero/helm-charts#320]
I am using Locust helm-chart but not able to stop the pods once the tests are completed. Is there any way to stop the pods as soon as tests are completed? 
Note:  I am running the tests in headless mode with 3m run-time.

**Comment by max-rocket-internet** [comment]
No there is not unless you manually scale the deployment to 0 replicas.

If you want to have a load test run to completion and then it would need to be run as a k8s  `Job` which the current version of the chart does not support. PRs welcome if someone wants to add this functionality 🙂
