### ISSUE TITLE
Wiremock documentation outdated

### ISSUE THREAD

**Issue by anoophp777** [deliveryhero/helm-charts#354]
Wiremock documentation seems outdated: https://artifacthub.io/packages/helm/deliveryhero/wiremock

For example:

`helm install my-wiremock deliveryhero/wiremock \
  --set consumer=my-consumer
  --set "consumer.stubs.my-service1-stubs=/mnt/my-service1-stubs" \
  --set "consumer.stubs.my-service2-stubs=/mnt/my-service2-stubs"`

There is no consumer, its consumer.name as per Default Values:

`consumer:
  name: example

  environment: {}

  args_include_default: true

  args: []

  stubs: {}

  initContainer: []

  initVolume: []`

Even the  files and mapping setting is incorrect. I need this to be updated. Unable to figure out how to load the files and mappings. 

Please help.

**Comment by max-rocket-internet** [comment]
Hi @anoophp777, it seems we have a problem syncing new versions of charts, I'm debugging it now...

**Comment by max-rocket-internet** [comment]
Hi @anoophp777
I've fixes the issue, it was related to https://github.com/helm/chartmuseum/issues/444
Can you recheck?
