### ISSUE TITLE
Latest chart releases sometimes aren't availabe in repo

### ISSUE THREAD

**Issue by z0rc** [deliveryhero/helm-charts#355]
I'm seeing strange behavior with this chart repo where latest chart releases are available for some time, but then gone.

For example at the moment of writing I don't see latest node-problem-detector release
```
% helm pull deliveryhero/node-problem-detector --version 2.2.3
Error: chart "node-problem-detector" matching 2.2.3 not found in deliveryhero index. (try 'helm repo update'): no chart version found for node-problem-detector-2.2.3
```
In the same time I can successfully download previous version 2.2.2.

Also observing similar behavior with cluster-overprovisioner.

**Comment by max-rocket-internet** [comment]
You're right @z0rc! I'm debugging it now.

**Comment by max-rocket-internet** [comment]
Hi @z0rc,
OK, I think I've resolved it, it was related to https://github.com/helm/chartmuseum/issues/444

Can you check again?

Also, note that chart version `2.2.3` of node-problem-detector uses docker image tag `v0.8.11` which seems to not exist yet: https://github.com/kubernetes/node-problem-detector/issues/692

**Comment by z0rc** [comment]
Thanks, chart repo behaves okay on my end now.

> chart version 2.2.3 of node-problem-detector uses docker image tag v0.8.11 which seems to not exist yet

Noticed this too, thanks for heads up.

**Comment by akuzni2** [comment]
@max-rocket-internet I'm noticing this behavior as well

```
[helm/chart-values]$ helm pull deliveryhero/locust --version 0.27.1
Error: chart "locust" matching 0.27.1 not found in deliveryhero index. (try 'helm repo update'): no chart version found for locust-0.27.1
[helm/chart-values]$ helm pull deliveryhero/locust --version 0.27.0
Error: chart "locust" matching 0.27.0 not found in deliveryhero index. (try 'helm repo update'): no chart version found for locust-0.27.0
```
is there a workaround for this?
