### ISSUE TITLE
feature request - Locust - add dnsConfig specifications as an option

### ISSUE THREAD

**Issue by akuzni2** [deliveryhero/helm-charts#369]
I'd like to add dnsConfig specifications into the master and worker deployment configuration sections.

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

this will help my team as we have some specific dns requirements.

would like to ask before I to attempt to do this.

**Comment by akuzni2** [comment]
bump

**Comment by max-rocket-internet** [comment]
Feel free to open a PR @akuzni2
