### ISSUE TITLE
Helm chart manifest is unavailable

### ISSUE THREAD

**Issue by szecsik** [deliveryhero/helm-charts#375]
Hi,

I'm trying to install the node problem detector helm chart, but looks like the package not found in the k8.gcr registry. Getting the below issue.

Failed to pull image "k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.11 not found: manifest unknown: Failed to fetch "v0.8.11" from request "/v2/node-problem-detector/node-problem-detector/manifests/v0.8.11"

Any alternative path?

Many Thanks

**Comment by max-rocket-internet** [comment]
https://github.com/deliveryhero/helm-charts/issues/372
