### ISSUE TITLE
[stable/node-problem-detector] new app version 0.8.12

### ISSUE THREAD

**Issue by jgournet** [deliveryhero/helm-charts#376]
Upstream issue https://github.com/kubernetes/node-problem-detector/issues/692 has been fixed and they released a new appVersion.
Would it be possible to update the helm chart version ?

Thank you in advance

**Comment by max-rocket-internet** [comment]
> Would it be possible to update the helm chart version ?

Sure, open a PR 🚀

**Comment by zestrells** [comment]
@jgournet This should now be solved 😄 https://github.com/deliveryhero/helm-charts/pull/379#event-7370838731
