### ISSUE TITLE
[stable/node-problem-detector] PSP API Versions Appear to Be Incorrect

### ISSUE THREAD

**Issue by justdan96** [deliveryhero/helm-charts#404]
I can see in https://github.com/deliveryhero/helm-charts/pull/315 that the PSP policy API version was changed for cluster versions over 1.21, however according to K8s documentation the PodSecurityPolicy object at the policy/v1beta1 API version is still fine up until 1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/

At the moment this causes issues since there is no PodSecurityPolicy object at the policy/v1 API version.

**Comment by max-rocket-internet** [comment]
Cool, PRs welcome 🙂
