### ISSUE TITLE
Submit Security Updates

### ISSUE THREAD

**Issue by whokilleddb** [deliveryhero/helm-charts#432]
Hi,
I am an independent security researcher who likes to help secure open source. I recently came across Helm charts during one of my projects and found some security issues in the source code. 

Could you add a SECURITY.md file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future. 

Looking forward to hearing from you 👍

**Comment by max-rocket-internet** [comment]
@whokilleddb generally we don't host the code that is used in the docker images for these helm charts. The docker images are made by other entities, usually in the `sources` section of `Chart.yaml`, for example [here](https://github.com/deliveryhero/helm-charts/blob/master/stable/toxiproxy/Chart.yaml#L23-L25).

But I will assign someone to take a look at your request.

**Comment by whokilleddb** [comment]
Thanks @max-rocket-internet! I am just happy to help.

**Comment by brennoo** [comment]
done in #440
