### ISSUE TITLE
Chart Repository is down

### ISSUE THREAD

**Issue by jandersen-plaid** [deliveryhero/helm-charts#447]
Hiya! It looks like the chart repository (https://charts.deliveryhero.io/) is down, any timeline on getting it back up and running?

**Comment by jandersen-plaid** [comment]
Ah, it is back! For whoever fixed it, thank you!

**Comment by max-rocket-internet** [comment]
Thanks for the notification. We were doing scheduled maintenance at this time 🙂

**Comment by jandersen-plaid** [comment]
> Thanks for the notification. We were doing scheduled maintenance at this time 🙂

Ah, nice! Is there a status page where I can subscribe to deliveryhero maintenance events? Would be great to know about so I don't go about making useless issues like this one.

**Comment by max-rocket-internet** [comment]
> Is there a status page where I can subscribe to deliveryhero maintenance events

We don't have one for the helm charts repo but it's a good idea, we'll look into it.

**Comment by jandersen-plaid** [comment]
Sounds good! Thanks for coming back around to update this!
