### ISSUE TITLE
kube-bench helm chart is not supporting batch/v1 API

### ISSUE THREAD

**Issue by joscabmar** [deliveryhero/helm-charts#452]
When installing it in EKS Kubernetes 1.25:

´´´
$ helm install kube-bench deliveryhero/kube-bench --set cronjob.schedule="5 * * * *" --namespace monitoring
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "kube-bench" namespace: "" from "": no matches for kind "CronJob" in version "batch/v1beta1"

$ kubectl api-resources | grep "cronjob"
cronjobs                          cj                      batch/v1                                  true         CronJob
´´´

**Comment by max-rocket-internet** [comment]
Cool, PRs welcome 🙂
