### ISSUE TITLE
[stable/node-local-dns] set hostNetwork as a variable

### ISSUE THREAD

**Issue by jgournet** [deliveryhero/helm-charts#466]
Hi,

Thanks for your helm charts !
Quick feature request for stable/node-local-dns: could you make hostNetwork a default value to true ?
(We're using "cilium network" and it needs to be set to false to make things work: https://docs.cilium.io/en/v1.10/gettingstarted/local-redirect-policy/#node-local-dns-cache )

And also: add some ways to add arguments so we can add -skipteardown=true, -setupinterface=false, and -setupiptables=false

thank you

**Comment by max-rocket-internet** [comment]
Pull requests are welcome @jgournet 😉

**Comment by jgournet** [comment]
closing as we're not going to use cilium anymore :)
