### ISSUE TITLE
[node-problem-detector] integrate optional grafana dashboard

### ISSUE THREAD

**Issue by jcpunk** [deliveryhero/helm-charts#478]
The grafana helm chart can import config maps with a specific label and annotation.

Would you consider including https://grafana.com/grafana/dashboards/15549-node-problem-detector/ as an optional dashboard I could load along with the helm chart?

**Comment by max-rocket-internet** [comment]
> as an optional dashboard I could load along with the helm chart?

Where would it go in the chart? It would just be a configmap?

**Comment by jcpunk** [comment]
> It would just be a configmap?

Yes, as an example: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-agent/dashboards-configmap.yaml

**Comment by max-rocket-internet** [comment]
Cool, looks good, just open a PR and ensure it's disabled by default 🙂

**Comment by jcpunk** [comment]
I'll see about putting this on my backlog, but I may not have time for a good while....

**Comment by mrclrchtr** [comment]
This would be really useful
