### ISSUE TITLE
[stable/locust] Guidance:  Automating a test on Locust including collection of results

### ISSUE THREAD

**Issue by MikeJansenNextira** [deliveryhero/helm-charts#520]
I am currently using the Locust Helm Chart.  I see the option to run it headless.  What I am missing is how I would launch a test via a script on headless install.  Do I just `kubectl exec` into the master pod using standard command line options?  Would this interact pooly with Locust already running on the master?

I would also like to automate collecting the results.  Everything going to a persistent volume would be sufficient.

I could not find any examples to do this.  I can work through and figure the pieces out.  But if there is an example or something I missed in the documentation, that would be very helpful.

The use case is straight forward:  Running a series of tests with different parameters, followed by processing the results.

**Comment by max-rocket-internet** [comment]
Does this help? https://github.com/deliveryhero/helm-charts/issues/446

**Comment by MikeJansenNextira** [comment]
@max-rocket-internet,

I ended up controlling it externally via REST API calls (I just snooped the calls the web UI was using).  This allows me to externally start swarming with the parameters I want, stop the testing after a specific time, and download the results.  It was more direct than trying to do the same via some Kubernetes magic.

Thanks for pointing me to that possible solution!
