### ISSUE TITLE
[stable/node-local-dns] make prometheus scraping optional

### ISSUE THREAD

**Issue by ami-descope** [deliveryhero/helm-charts#525]
There are cases where prometheus endpoints are continuously being scraped by services like Datadog

We need the option to be able to turn them off as this can increase costs on custom metrics by Datadog

Currently, the chart allows you to enabled serviceMonitor and skip the Promethues annotations from the service, but this can cause an error when service monitor CRD is not installed in the cluster.

**Comment by max-rocket-internet** [comment]
Cool, pull requests welcome 🙂
