### ISSUE TITLE
[stable/prometheus-locust-exporter] ".helmignore " filename blocking Windows import

### ISSUE THREAD

**Issue by ACandian** [deliveryhero/helm-charts#527]
Hi,

The .helmignore file in stable/prometheus-locust-exporter ends with a space, making it ".helmignore ".
Since Windows doesn't allow spaces at the end of filenames, it prevents proper cloning of the repository for Windows users.

**Comment by max-rocket-internet** [comment]
Cool, PRs welcome. It probably would've been quicker to open a PR than to write this issue 😅

**Comment by ACandian** [comment]
No worries, do I still bump the Chart's version, even tough there is no change to the Chart itself ?
I'll need probably need to do it from a non-Windows machine, the previous PR was a nightmare to pull-up while ignoring this specific file 😅.

**Comment by max-rocket-internet** [comment]
> No worries, do I still bump the Chart's version, even tough there is no change to the Chart itself ?

Yep, no chart changes can be merged without version bump, it's checked in CI.
