### ISSUE TITLE
node-problem-detector 0.8.14 arm64 image issue

### ISSUE THREAD

**Issue by edwardchenchen** [deliveryhero/helm-charts#532]
node-problem-detector 2.3.11 chart
updated by 
https://github.com/deliveryhero/helm-charts/commit/2ba53be34c5d826395892fe9f56096c9fe8aabec
has this problem in 0.8.14 arm64 image 
https://github.com/kubernetes/node-problem-detector/issues/797
```
/bin/sh: 1: exec: /node-problem-detector: Exec format error
```

**Comment by PCCS-CBA** [comment]
This was reported in the upstream "node-problem-detector' GitHub https://github.com/kubernetes/node-problem-detector/issues/827. Looks like they have just fixed the issue with a new release of node-problem-detector 0.8.15. Hopefully we will get an updated helm chart with this fix soon from Delivery Hero.

**Comment by stafot** [comment]
We can just bump the default app version to be v0.8.15 this could fix the issue. I did this on my side and worked.
