### ISSUE TITLE
[stable/node-problem-detector] Send events to a namespace other than default

### ISSUE THREAD

**Issue by pavlovnicola** [deliveryhero/helm-charts#533]
Hi,

By default, running the following command:

`helm install --generate-name deliveryhero/node-problem-detector --namespace health`

would create the DaemonSet as well as the pods under the "health" NS, but still events go to default.

From the https://github.com/kubernetes/node-problem-detector and according to https://github.com/kubernetes/node-problem-detector/issues/476, this is supported by adding "**--event-namespace**"

How do I add this with helm?

**Comment by max-rocket-internet** [comment]
> How do I add this with helm?

You can add this command line argument here in your values: https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/values.yaml#L40

**Comment by pavlovnicola** [comment]
Hi @max-rocket-internet ,

Thanks for the reply.  It worked. I used the following _values.yaml_ snippet:

`settings:
  extraArgs:
  - --event-namespace health`
