### ISSUE TITLE
[k8s-event-logger] option to change the container name 

### ISSUE THREAD

**Issue by shehbazk** [deliveryhero/helm-charts#540]
Can a variable be added inside the values.yaml such as conrtainerName which allows the deployment container name value to be set from the values.yaml file currently its hard coded to "app" (which doesn't add any value) and requires a downloading the templates and making the change manually?

Default value for this could be k8seventlogger or similar?

**Comment by max-rocket-internet** [comment]
Yes, just open a PR 🙂
