### ISSUE TITLE
HTTP 504 response from charts.deliveryhero.io

### ISSUE THREAD

**Issue by hkan** [deliveryhero/helm-charts#554]
Hello,

The ChartMuseum instance you're running on charts.deliveryhero.io has been responding with HTTP 504 for pretty much all endpoints since earlier today.

I'm not sure if this is the correct place to mention this, I didn't know where else to post.

**Comment by max-rocket-internet** [comment]
Hey @hkan,
I've applied a short term fix. Is the issue resolved for you?

**Comment by max-rocket-internet** [comment]
OK nice. One of our chart museum pods had some I/O errors. Seems to be OK now. Thanks for reporting it.

**Comment by max-rocket-internet** [comment]
Hmmm I see we are periodically throwing 499s

![image](https://github.com/deliveryhero/helm-charts/assets/8859277/2776ce82-f95b-47f0-af50-c0c598b417e6)

**Comment by pierluigilenoci** [comment]
@max-rocket-internet, could you please take a look at this
https://github.com/max-rocket-internet/k8s-event-logger/pull/45

**Comment by max-rocket-internet** [comment]
I've applied some changes but still not sure what the root cause is. I'll leave this open, let me know if there's further problems.

**Comment by pierluigilenoci** [comment]
@max-rocket-internet, my comment (and the linked PR) was relevant because it allows everyone to have a more resilient Chart Museum than Rocket's.

**Comment by pierluigilenoci** [comment]
For me, this is still an issue.

**Comment by pierluigilenoci** [comment]
This is still an issue.

**Comment by pierluigilenoci** [comment]
This is still an issue.

**Comment by max-rocket-internet** [comment]
@pierluigilenoci how often are you seeing this?

e.g. if I run this:

```shell
while true; do curl -w "%{response_code} %{time_total}\n" -s -o /dev/null https://charts.deliveryhero.io/index.yaml ; done
```

For me it's solid, left it running for about an hour, it's all like this:

```
200 0.297999
200 0.214413
200 0.177474
200 0.294827
200 0.310920
```

**Comment by pierluigilenoci** [comment]
It still needs to be resolved. 
It happened once in a while, and it could happen again. 
What is DeliveryHero's Chart Registry SLA?

Possible solution? https://github.com/max-rocket-internet/k8s-event-logger/pull/45

**Comment by pierluigilenoci** [comment]
No action corresponds to no solution.

**Comment by pierluigilenoci** [comment]
No solution corresponds to the problem that is still present.

**Comment by max-rocket-internet** [comment]
@pierluigilenoci as I mentioned [here](https://github.com/deliveryhero/helm-charts/issues/554#issuecomment-1923825329), it would be helpful to have more info from your side.

> It happened once in a while

Is not helpful 🙂

Please run the command mentioned for a few hours or a day and post the results.

**Comment by jjesusglia** [comment]
This is happening again, is there a planned fix? Thanks!

**Comment by pierluigilenoci** [comment]
@max-rocket-internet As I wrote last spring, the problem has not been solved, and it happened again.
Ref:  #606 
The solution: #591
