### ISSUE TITLE
Vulnerabilities detected

### ISSUE THREAD

**Issue by LMantovan** [deliveryhero/helm-charts#558]
Hi,
I'm using the latest helm chart version of kube-downscaler https://artifacthub.io/packages/helm/deliveryhero/kube-downscaler but the image is full of vulnerabilities as the image below
![image](https://github.com/deliveryhero/helm-charts/assets/129963170/550a26c7-e934-4718-a1e0-6c1ff219acb3)
Is it possible to solve some of them? Maybe the critical and the high?

**Comment by max-rocket-internet** [comment]
Hi @LMantovan 👋
We are only hosting a helm chart for `kube-downscaler`, we are not responsible for the code itself or its docker image. If you go to the [helm chart path](https://github.com/deliveryhero/helm-charts/tree/master/stable/kube-downscaler), you can see there the homepage is https://codeberg.org/hjacobs/kube-downscaler

I suggest you follow it up there.
