### ISSUE TITLE
[kube-bench] Upgrade to CIS v1.5.0 to GKE

### ISSUE THREAD

**Issue by YoannR5** [deliveryhero/helm-charts#565]
We tried to run kube-bench by modifying the helm-chart to CIS version 1.5.0, but got the following error: 
"error validating targets: No targets configured for gke-1.5.0"
It seems that the CIS 1.5.0 package is not available. 

Is is possible to upgrade the chart with CIS guide version 1.5.0 ? 

Thank you !

**Comment by stephaneetje** [comment]
👍 
Also interested in that upgrade for our 1.29 kubernetes clusters

**Comment by max-rocket-internet** [comment]
PRs welcome 🙂

**Comment by YoannR5** [comment]
Any news on the subject ? :)

**Comment by max-rocket-internet** [comment]
> Any news on the subject ? :)

PRs from @YoannR5 or anyone welcome at any time but for now I'll close
