### ISSUE TITLE
Publish helm chart also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by nlamirault** [deliveryhero/helm-charts#591]
Could you push the packaged Helm chart also on ghcr.io, so we can pull/install the helm chart like this:

```
helm install xxx oci://ghcr.io/xxxxxxxx --version x.y.z
```

**Comment by max-rocket-internet** [comment]
Why? What's the difference?

**Comment by pierluigilenoci** [comment]
@max-rocket-internet the difference: #554 and #606
