### ISSUE TITLE
Bump AppVersion in node-problem-detector chart

### ISSUE THREAD

**Issue by cmontemuino** [deliveryhero/helm-charts#602]
Current `AppVersion` of node-problem-detector is `v0.8.18`, but a new version has been released a couple of months ago: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.19

Changing https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/Chart.yaml#L4 and https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/values.yaml#L59 is all what's needed.

**Comment by cmontemuino** [comment]
I can open a PR with the changes if that's ok.

**Comment by max-rocket-internet** [comment]
PRs are always welcome @cmontemuino 🙂

**Comment by cmontemuino** [comment]
Opened a PR to bump the chart: https://github.com/deliveryhero/helm-charts/pull/610
