### ISSUE TITLE
https://charts.deliveryhero.io/index.yaml does not respond

### ISSUE THREAD

**Issue by msvticket** [deliveryhero/helm-charts#606]

**Comment by msvticket** [comment]
In a browser the result looks like this:

<img width="1180" alt="Screenshot of https://charts.deliveryhero.io/index.yaml" src="https://github.com/user-attachments/assets/4783ca09-6ed8-4be8-9e76-41c0edd891fc">

**Comment by msvticket** [comment]
I suggest you migrate to using Github pages or ghcr (OCI) to host the charts. But that is of course more a of a long term solution...

**Comment by msvticket** [comment]
See #591 and #554

**Comment by gp42** [comment]
Experiencing the same problem.

**Comment by max-rocket-internet** [comment]
I'm checking...

**Comment by max-rocket-internet** [comment]
I've restarted the chartmuseum pods, seems to be fine now.

> I suggest you migrate to using Github pages

Github pages is not really possible with our large Github org

> ghcr (OCI) to host the charts

This is a good idea, it was also mentioned in https://github.com/deliveryhero/helm-charts/issues/591

**Comment by max-rocket-internet** [comment]
Follow in https://github.com/deliveryhero/helm-charts/issues/607

**Comment by nathanmcgarvey-modopayments** [comment]
FWIW, AWS ECR also supports OCI charts, I believe, though GHCR may be more idiomatic in this case.
