### ISSUE TITLE
Move to a more reliable chart hosting solution

### ISSUE THREAD

**Issue by max-rocket-internet** [deliveryhero/helm-charts#607]
We have periodic problems with chartmuseum running on k8s, e.g:
https://github.com/deliveryhero/helm-charts/issues/606
https://github.com/deliveryhero/helm-charts/issues/554

GHCR has [been suggested](https://github.com/deliveryhero/helm-charts/issues/591) as a good option.

**Comment by pierluigilenoci** [comment]
@max-rocket-internet, you have already some PR ready to fix this:
https://github.com/max-rocket-internet/k8s-event-logger/pull/45

**Comment by shubhamv1436** [comment]
@max-rocket-internet Its still happening. Anything you can do to continuously monitor and automate the fix.

```
helm repo add deliveryhero https://charts.deliveryhero.io/
Error: looks like "https://charts.deliveryhero.io/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.deliveryhero.io/index.yaml : 504 Gateway Timeout
```

**Comment by msvticket** [comment]
Considering that you have Cloudflare configured as CDN in front of the Chartmuseum a quick work around (while working on a long term solution) should be to configure Cloudflare to serve content even though it is is stale (i.e. isn't valid according to cache headers).

**Comment by bunnybilou** [comment]
You might want to consider adding caching on Cloudflare to reduce the need for frequent origin fetches.

I checked the Argo Helm repository, and they have a max-age of 600 seconds configured for caching: https://argoproj.github.io/argo-helm/index.yaml

**Comment by max-rocket-internet** [comment]
I would be grateful if everyone could take a look at [this PR](https://github.com/deliveryhero/helm-charts/pull/612) 😄

**Comment by msvticket** [comment]
Unfortunately it doesn't work properly; there seem to be some kind of permission problem:

```
$ helm template oci://ghcr.io/deliveryhero/helm-charts/node-local-dns
Error: GET "https://ghcr.io/v2/deliveryhero/helm-charts/node-local-dns/tags/list": GET "https://ghcr.io/token?scope=repository%3Adeliveryhero%2Fhelm-charts%2Fnode-local-dns%3Apull&service=ghcr.io": unexpected status code 401: unauthorized: authentication required
```

It is not a general problem with ghcr. An example of another repository that works is oci://ghcr.io/bank-vaults/helm-charts/vault-operator

**Comment by msvticket** [comment]
Another problem is that the instructions are incomplete:

```
$ helm install oci://ghcr.io/deliveryhero/helm-charts/node-local-dns
Error: INSTALLATION FAILED: must either provide a name or specify --generate-name
```

**Comment by max-rocket-internet** [comment]
> Unfortunately it doesn't work properly; there seem to be some kind of permission problem:

The problem is internal, I need to change the visibility of the packages, this will take me some time 🕒

**Comment by max-rocket-internet** [comment]
> The problem is internal, I need to change the visibility of the packages, this will take me some time 🕒

Fixed

> Another problem is that the instructions are incomplete:

Fixed
