### ISSUE TITLE
[stable/k8s-event-logger] - latest chart not avaiable

### ISSUE THREAD

**Issue by jaimin-shah-fs** [deliveryhero/helm-charts#611]
There was an update to the stable chart for k8s-event-logger yesterday, but when accessing `https://chart.deliveryhero.io/index.yaml` the latest version still shows 1.1.7 instead of 1.1.8. Is there a delay in chartmuseum before the chart is available publically?

**Comment by max-rocket-internet** [comment]
Yes, there's a temporary cache in place, see https://github.com/deliveryhero/helm-charts/issues/607, I'll hopefully have a fix today 🙏

**Comment by max-rocket-internet** [comment]
@jaimin-shah-fs can you please check with the new OCI hosted chart: https://github.com/deliveryhero/helm-charts/tree/master/stable/k8s-event-logger#how-to-install-this-chart
