### ISSUE TITLE
node-local-dns ConfigMap deletion

### ISSUE THREAD

**Issue by jem41** [deliveryhero/helm-charts#623]
Hello,

We use Azure Kubernetes Service with Azure CNI Networking. With the `addonmanager.kubernetes.io/mode: Reconcile` label on the node-local-dns' ConfigMap, the resource gets deleted shortly after a Helm upgrade. Is it intentional for the ConfigMap to be removed? If so, how are these values read if nodes scale out or a pod restarts?

We recently added ArgoCD to our cluster and the ConfigMap's deletion causes node-local-dns to perpetually be OutOfSync. If deletion is intentional, would you accept a PR to allow specifying annotations to the ConfigMap? That would allow us to ignore the resource in ArgoCD for sync purposes.

**Comment by jem41** [comment]
I'm happy to open a PR for the annotation portion, but it would be helpful to know if the reconcile label resulting in the deletion of the ConfigMap is as intended as well. If not, that label could be made optional to avoid deletion.

**Comment by max-rocket-internet** [comment]
> I'm happy to open a PR for the annotation portion

If you can just open a PR to add annotations to the `configMap` but leave the default value blank then this would solve your problem, right @jem41?

**Comment by max-rocket-internet** [comment]
I'm not sure TBH but you are of course welcome to make a PR to add annotations 🙂

**Comment by z0rc** [comment]
`addonmanager.kubernetes.io` lables are used by Cluster Addon Manager and intedned to use when resources are installed with Manager. It doesn't make sense to have those lables for resources installed with Helm.

Git blame shows that those lables were introduced by initial version of node-local-dns chart, so I assume they were copy-pasted without much consideration from [original yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml).

On the side note, it's interesting that AKS still uses addon manager, as nowadays it's considered as an arifact of kubernetes early years.
