### ISSUE TITLE
[stable/locust] Passing arguments to the master/worker docker-entrypoint.sh scripts

### ISSUE THREAD

**Issue by KaneRodriguez** [deliveryhero/helm-charts#77]
I have args that I want to pass to the `docker-entrypoint.sh` scripts ran on both the master and worker pods. 

Can either the [configmap-config.yaml](https://github.com/deliveryhero/helm-charts/blob/68cd7b7a72fdc9ed91fd2fd635111aadf14f09c7/stable/locust/templates/configmap-config.yaml) or the [worker/master-deployment.yaml](https://github.com/deliveryhero/helm-charts/blob/68cd7b7a72fdc9ed91fd2fd635111aadf14f09c7/stable/locust/templates/worker-deployment.yaml#L42) files be updated to support this?

Or is the intent that the `command` value can be overridden somehow.

**Comment by max-rocket-internet** [comment]
I actually have this already in a branch. I'll push it and create a PR.

**Comment by max-rocket-internet** [comment]
@KaneRodriguez let me know if the merged PR doesn't work for you.
